#ADD TWO NUMBERS USING MEMORY POINTER (M)

MVI C,00H     # ASSUME CARRY 0
LXI H,2000H
MOV A,M
INX H              #INCREMENT H == 2001
ADD M
JNC SKIP       #JUMP IF NO CARRY
INR C            #INCREMENT C
SKIP: INX H
MOV M,A
INX H            #H==2003
MOV M,C
HLT