//ADD SERIES OF NUMBERS IN A BLOCK AND DEAL WITH CARRY TOO

LXI H,2000H
MVI C,0AH
MVI A,00H       //SUM
MVI B,00H       //CARRY

BACK: ADD M
JNC SKIP
INX B                 //INCREMENT IF CARRY
SKIP: INX H
DCR C
JNZ BACK
MOV M,A
INX H
MOV M,B
HLT