//FIND HIGHEST NUMBER IN A MEMORY BLOCK

LXI H,2000H
MVI C,0AH         //INITIALIZATION PART
MVI A,00H

BACK: CMP M      //COMPARE A AND M (A-M)
JNC SKIP
MOV A,M
SKIP: INX H
DCR C
JNZ BACK
MOV M,A
HLT